kind: Deployment 
apiVersion: extensions/v1beta1
metadata:
  namespace: default 
  name: log-generator 
  labels:
    app: log-generator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: log-generator 
    spec:
      containers:
        - name: log-generator 
          image: centos:7 
          command: ["/workspace/entrypoint.sh"]
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: entrypoint
              mountPath: /workspace
              readOnly: true
      nodeSelector:
        beta.kubernetes.io/fluentd-ds-ready: "true"
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: entrypoint 
          configMap:
            name: log-generator-config 
            defaultMode: 0755
