kind: Deployment 
apiVersion: extensions/v1beta1
metadata:
  namespace: default 
  name: file-log 
  labels:
    app: file-log
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: file-log 
    spec:
      containers:
        - name: file-log 
          image: centos:7 
          imagePullPolicy: IfNotPresent 
          command: ["/workspace/entrypoint.sh"]
          args:
            - -l
            - /cached/access.log 
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: entrypoint
              mountPath: /workspace
              readOnly: true
            - name: cached 
              mountPath: /cached
        - name: logger 
          image: alpine:latest 
          imagePullPolicy: IfNotPresent 
          command: ["tail"]
          args:
            - -f
            - /cached/access.log 
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: entrypoint
              mountPath: /workspace
              readOnly: true
            - name: cached 
              mountPath: /cached
      nodeSelector:
        beta.kubernetes.io/fluentd-ds-ready: "true"
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: entrypoint 
          configMap:
            name: file-log-config 
            defaultMode: 0755
        - name: cached 
          emptyDir: {}
